apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fe-deployment
  template:
    metadata:
      labels:
        app: fe-deployment
    spec:
      containers:
      - name: fe-deployment
        image: june050312/fe:v1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
