apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: goods-service-monitor
  labels:
     app: goods-service
spec:
  selector:
    matchLabels:
      app: goods-service
  endpoints:
  - port: "goods-service"
    path: /api/goods/metrics