apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: purchase-service-monitor
  labels:
     app: purchase-service
spec:
  selector:
    matchLabels:
      app: purchase-service
  endpoints:
  - port: "purchase-service"
    path: /api/purchase/metrics